// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYwUhA4YS-KiyM-z4xpd-HfzpT7cU9jnY',
    appId: '1:301777066204:web:262bf0f9a7ff9990eafc19',
    messagingSenderId: '301777066204',
    projectId: 'grocery-ai-app-d8e45',
    authDomain: 'grocery-ai-app-d8e45.firebaseapp.com',
    storageBucket: 'grocery-ai-app-d8e45.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYwUhA4YS-KiyM-z4xpd-HfzpT7cU9jnY',
    appId: '1:301777066204:android:262bf0f9a7ff9990eafc19',
    messagingSenderId: '301777066204',
    projectId: 'grocery-ai-app-d8e45',
    storageBucket: 'grocery-ai-app-d8e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwUhA4YS-KiyM-z4xpd-HfzpT7cU9jnY',
    appId: '1:301777066204:ios:262bf0f9a7ff9990eafc19',
    messagingSenderId: '301777066204',
    projectId: 'grocery-ai-app-d8e45',
    storageBucket: 'grocery-ai-app-d8e45.firebasestorage.app',
    iosBundleId: 'com.aibuddy.app.aiStudyBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwUhA4YS-KiyM-z4xpd-HfzpT7cU9jnY',
    appId: '1:301777066204:macos:262bf0f9a7ff9990eafc19',
    messagingSenderId: '301777066204',
    projectId: 'grocery-ai-app-d8e45',
    storageBucket: 'grocery-ai-app-d8e45.firebasestorage.app',
    iosBundleId: 'com.aibuddy.app.aiStudyBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYwUhA4YS-KiyM-z4xpd-HfzpT7cU9jnY',
    appId: '1:301777066204:windows:262bf0f9a7ff9990eafc19',
    messagingSenderId: '301777066204',
    projectId: 'grocery-ai-app-d8e45',
    authDomain: 'grocery-ai-app-d8e45.firebaseapp.com',
    storageBucket: 'grocery-ai-app-d8e45.firebasestorage.app',
    measurementId: 'G-MEASUREMENT_ID',
  );
}